name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and deploy
      run: |
        git config user.name "Jasper Spahl"
        git config user,email "jasperspahl@web.de"
        npm install yarn
        yarn install
        yarn build
        yarn deploy
      env:
        CI: true
